version: '3'

services:
  backend:
    user: "${UID}:${GID}"
    build:
      context: .
      dockerfile: dockerfiles/responder
    ports:
      - "${BACKEND_PORT}:${BACKEND_PORT}"
    volumes:
      - ./src/backend:/opt/backend
    environment:
      - PORT=${BACKEND_PORT}
      - DEBUG=1
      - PYTHONPATH=/opt/backend
  frontend:
    user: "${UID}:${GID}"
    build:
      context: .
      dockerfile: dockerfiles/vuejs
    entrypoint: /entrypoint.sh
    depends_on:
      - backend
    ports:
      - "${FRONTEND_PORT}:8080"
    volumes:
      - ./src/frontend:/opt/frontend
    environment:
      - HOST=0.0.0.0
      - PORT=8080
      - CHOKIDAR_USEPOLLING=true
      - API_HOST=${BACKEND_RUNNING_ON_HOST}
      - API_PORT=${BACKEND_RUNNING_ON_PORT}